# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "jakelinebissani/centos7Min"
  config.vm.box_version = "1.0"

   config.vm.define :web do |web_config|
    web_config.vm.network "private_network", ip: "192.168.1.101"
  end

   config.vm.provider "virtualbox" do |vb|

     vb.memory = "3064"
     vb.customize ["modifyvm", :id, "--cpus", 2]
     vb.name = "node01"

   end
end
